name: Build APK

on:
  workflow_call:
    outputs:
      build_status:
        description: "APK build status"
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.setstatus.outputs.status }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Set status output
        id: setstatus
        run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
