name: Lints

on:
  workflow_call:
    outputs:
      lint_status:
        description: "Status of lint job"
        value: ${{ jobs.lint.outputs.status }}

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.setstatus.outputs.status }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: chmod +x gradlew

      - name: Run Lint
        id: runlint
        run: ./gradlew lintDebug --no-daemon

      - name: Set status output
        id: setstatus
        run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT

      - name: Upload Lint Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/
